version: 2

models:
  - name: ent_sfdc_geo_pubsec_segment
    description: A user entitlement table based on user's Geo segment in Salesforce. It is used for row level security in Tableau. We have created a new geo_pubsec_segment column to align with the FY26 launch which brings the PubSec geo into Amer - the addition of this column will allow analysts to use it as the join key - subsequently allowing PubSec access to only people with a geo of Amer and a sales segment of PubSec.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_email
            - geo_pubsec_segment
    columns:
      - name: user_email
        data_tests: 
            - not_null
      - name: geo_pubsec_segment
        data_tests: 
            - not_null
      - name: entitlement_basis

  - name: ent_sfdc_account_manager_hierarchy
    description: A model that captures account entitlements based on management hierarchy and geographical access rules. It combines direct ownership relationships (including manager chain up to 3 levels) with geo-based access permissions, ensuring users who are account owners or in their management chain have appropriate access while maintaining separate geo-based access for non-owners.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - dim_crm_account_id
            - user_email
            - entitlement_basis
    columns:
      - name: dim_crm_account_id
        description: The unique identifier for the CRM account
        data_tests:
          - not_null
      - name: user_email
        description: The email address of the user with account access
        data_tests:
          - not_null
      - name: geo_pubsec_segment
        description: The geographical or public sector segment associated with the account access
      - name: entitlement_basis
        description: The basis for the entitlement (either 'account_ownership' for direct/management chain access or 'geo' for geographical access)
        data_tests:
          - not_null
  
  - name: prep_crm_account
    description: '{{ doc("prep_crm_account") }}'
    columns:
      - name: dim_crm_account_id
        description: account id from SFDC identifing the customer
      - name: crm_account_name
        description: account name from SFDC
      - name: crm_account_country
        description: billing country of SFDC account
      - name: dim_parent_crm_account_id
        description: ultimate parent account id
      - name: ultimate_parent_account_name
        description: parent account name
      - name: ultimate_parent_account_segment
        description: Sales segment of the parent account
      - name: ultimate_parent_billing_country
        description: billing country of parent account
      - name: record_type_id
      - name: gitlab_com_user
      - name: is_jihu_account
      - name: account_owner
      - name: account_owner_team
      - name: account_type
      - name: gtm_strategy
      - name: technical_account_manager
      - name: is_deleted
        description: flag indicating if account has been deleted
      - name: is_reseller
        description: Identify whether a crm_account is a reseller.
      - name: merged_to_account_id
        description: for deleted accounts this is the SFDC account they were merged to
      - name: crm_account_created_date
        description: The date on which the CRM account was created in SFDC
      - name: gs_health_csm_sentiment 
        description: This is what the TAM thinks the health of this account should be - Formerly was just Health Score - Gainsight is the SSOT for this field and its value can only be updated in Gainsight.
      - name: tam_manager
        description: The name of the manager for the tehchnical account manager who manages the account
      - name: executive_sponsor
        description: executive sponsor of this account

